### ISSUE TITLE
io/to-geojson throwing error from io/read-wkt

### ISSUE THREAD

**Issue by rasensio1** [Factual/geo#13]
Hi friends,

Converting a wkt file to geojson using:

```clojure
(-> wkt-obj
    geo.io/read-wkt ; works fine
    geo.io/to-geojson) ; fails here
```
and `to-geojson` is throwing the following error:
```
NoSuchMethodError com.fasterxml.jackson.databind.JavaType.isReferenceType()Z  com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2 (BeanSerializerFactory.java:205)
```

I saw some things about jackson deps mismatch in my search, but was wondering if you guys had any other ideas.

Cheers,

**Comment by willcohen** [comment]
Both this and the reported error in #11 look to me like they may be due to something outside of this library using a version of jackson older than 2.6.0: https://github.com/FasterXML/jackson-databind/issues/1101.

Are you using gorilla-repl, like in #11? That dependency's 0.4.0 uses cheshire 5.3.1, which [uses jackson 2.3.1](https://github.com/dakrone/cheshire/blob/254900a9a22b8fe42ed106b0ae03df75a19e018f/project.clj).

1.2.1 of this library uses jackson 2.8.4, and #12 would bump it to 2.9.5.

**Comment by rasensio1** [comment]
@willcohen  Thanks for that.
I was using ring-json 0.4.0 , which uses jackson 2.5.3

Cheers!
